use-grammars = { except = ["hare"] }

[[language]]
name = "rust"

[language.config]
checkOnSave = { command = "clippy" }

[[language]]
name = "cpp"
auto-format = true
file-types = ["cc", "c++", "cpp", "hpp", "cxx", "hxx", "C", "H"]
comment-token = "//"
